name: 'Setup'
description: 'Checks out code and sets up the JDK'
runs:
  using: "composite"
  steps:

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      shell: bash
