[versions]
activityCompose = "1.4.0"
anvil = "2.4.0"
appCompat = "1.4.1"
composeCompiler = "1.1.1"
compose = "1.1.1"
composeNavigation = "2.4.1"
coroutines = "1.6.0"
dagger = "2.41"
doctor = "0.8.0"
gradlePlugins-agp = "7.2.0-alpha07"
gradlePlugins-buildLogic = "0.0.1-SNAPSHOT"
gradlePlugins-junit5 = "1.8.2.0"
gradlePlugins-ktlint = "10.2.1"
googlejavaformat = "1.13.0"
jupiter = "5.8.2"
kotlin = "1.6.10"
kover = "0.5.0"
leakcanary = "2.8.1"
lifecycle = "2.4.0"
lifecycleViewmodelCompose = "2.4.0"
moduleGraphAssertion = "2.2.0"
startup = "1.1.0"
store = "4.0.4-KT15"
timber = "5.0.1"
turbine = "0.7.0"
truth = "1.1.3"
versionUpdate = "0.41.0"

[plugins]
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-lifecycle-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
anvil-annotations = { module = "com.squareup.anvil:annotations", version.ref = "anvil" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
google-dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
google-dagger-daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
gradlePlugins-android = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugins-agp" }
gradlePlugins-buildLogic = { module = "com.github.vichid:android-build-logic", version.ref = "gradlePlugins-buildLogic" }
gradlePlugins-junit5 = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "gradlePlugins-junit5" }
gradlePlugins-moduleGraphAssertion = { module = "com.jraska.module.graph.assertion:plugin", version.ref = "moduleGraphAssertion" }
gradlePlugins-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugins-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "gradlePlugins-ktlint" }
gradlePlugins-versionUpdate = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionUpdate" }
googlejavaformat = { module = "com.google.googlejavaformat:google-java-format", version.ref = "googlejavaformat" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
store = { module = "com.dropbox.mobile.store:store4", version.ref = "store" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[bundles]
compose = ["androidx-compose-compiler", "androidx-compose-foundation", "androidx-compose-material", "androidx-compose-materialIconsExtended", "androidx-compose-runtimeLivedata", "androidx-compose-ui", "androidx-compose-uiTooling"]
lifecycle = ["androidx-lifecycle-lifecycleRuntimeKtx", "androidx-lifecycle-lifecycleViewmodelCompose"]
unitTests = ["jupiter-api", "jupiter-params", "truth", "turbine", "kotlin-coroutines-test"]
