[versions]
activityCompose = "1.4.0"
anvil = "2.4.0"
appCompat = "1.4.1"
benchmark = "1.1.0-rc01"
composeCompiler = "1.2.0-beta01"
compose = "1.2.0-alpha07"
composeNavigation = "2.4.2"
coroutines = "1.6.1"
dagger = "2.42"
gradlePlugins-buildLogic = "0.0.6"
gradlePlugins-junit5 = "1.8.2.0"
inject = "1"
jupiter = "5.8.2"
kotlin = "1.6.20"
leakcanary = "2.9.1"
lifecycle = "2.4.1"
lifecycleViewmodelCompose = "2.4.1"
startup = "1.1.1"
store = "4.0.5"
timber = "5.0.1"
turbine = "0.7.0"
truth = "1.1.3"

[plugins]
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }

[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-benchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-uiGraphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
androidx-compose-uiText = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-lifecycle-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
anvil-annotations = { module = "com.squareup.anvil:annotations", version.ref = "anvil" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
google-dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
google-dagger-daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
gradlePlugins-buildLogic = { module = "com.github.vichid:android-build-logic", version.ref = "gradlePlugins-buildLogic" }
gradlePlugins-junit5 = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "gradlePlugins-junit5" }
inject-annotations = { module = "javax.inject:javax.inject", version.ref = "inject" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
store = { module = "com.dropbox.mobile.store:store4", version.ref = "store" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[bundles]
unitTests = ["jupiter-api", "jupiter-params", "truth", "turbine", "kotlin-coroutines-test"]
