#!/bin/bash

echo "Running detekt check..."
fileArray=($@)
detektInput=$(
    IFS=,
    printf "%s" "${fileArray[*]}"
)

if [ -z "$detektInput" ]; then
    echo "No input files"
else
    echo "Input files: $detektInput"

    OUTPUT=$(detekt --input "$detektInput" 2>&1)
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        echo "$OUTPUT"
        echo "***********************************************"
        echo "                 Detekt failed                 "
        echo " Please fix the above issues before committing "
        echo "***********************************************"
        exit $EXIT_CODE
    fi
fi
