name: 'Gradle Cache'
description: 'Cache Gradle Build Cache to improve workflow execution time'
inputs:
  key-prefix:
    description: 'A prefix on the key used to store/restore cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate cache key
      shell: bash
      run: chmod +x scripts/checksum.sh ; ./scripts/checksum.sh checksum.txt

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/build-cache-*
        key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-