name: 'Gradle Cache'
description: 'Cache Gradle Build Cache to improve workflow execution time'
inputs:
  key-prefix:
    description: 'A prefix on the key used to store/restore cache'
    required: true
runs:
  using: "composite"
  steps:

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/build-cache-*
        key: ${{ runner.os }}-${{ inputs.key-prefix }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.key-prefix }}-
