name: Main
on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate build number
        shell: bash
        run: echo "BUILD_NUMBER=$(expr $GITHUB_RUN_NUMBER + 5210)" >> $GITHUB_ENV

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Build and check
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            app:assembleDebug
            app:lintRelease

      - name: Upload build outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs
