name: Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'server/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Validate
        uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: android-app:app:assembleDebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
#      - name: Upload build outputs
#        if: success()
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-outputs
#          path: android-app/app/build/outputs
