name: buildbot

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests with Gradle
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: test --continue --no-daemon
