name: Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'server/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: android-app:app:assembleDebug

#      - name: Upload build outputs
#        if: success()
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-outputs
#          path: android-app/app/build/outputs
