name: Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'server/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Build and check
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            android-app:app:assembleDebug
            android-app:app:lintRelease

#      - name: Upload build outputs
#        if: success()
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-outputs
#          path: android-app/app/build/outputs
