name: Diffuse
on: [ pull_request ]

jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Build Master
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk/master
          path: app/build/outputs/apk/debug/app-master.apk

  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Build PR
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk/pr
          path: app/build/outputs/apk/debug/app-pr.apk

  diffuse:
    needs: [ build-master, build-pr ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download APKs
        uses: actions/download-artifact@v2
        with:
          name: apk

      - id: diffuse
        uses: usefulness/diffuse-action@v1
        with:
          old-file-path: apk/master/app-debug.apk
          new-file-path: apk/pr/app-debug.apk
