name: Publish detekt rules package to GitHub Packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :detekt-rules:publish -Pbuild.logic.path=build-logic -Pdetekt.rules.path=../detekt-rules --no-configuration-cache
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
