name: Publish detekt rules package to GitHub Packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :detekt-rules:publish --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
