name: PR
on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  validate-wrapper:
    name: 🏗 Validate wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  code-linting:
    name: 🧹 Code linting
    needs: validate-wrapper
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: detekt
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif

  tests:
    name: 🧪 Run unit tests
    needs: code-linting
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: testDebugUnitTest koverXmlReport
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy test results
        if: failure()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: junit
  #
  #      - name: Upload coverage artifacts
  #        if: always()
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: coverage
  #          path: build/reports/kover

  #      - name: Codecov coverage
  #        uses: codecov/codecov-action@v3
  #        with:
  #          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: 🔨 Build
    needs: code-linting
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: assertModuleGraph android-app:app:assembleDebug android-app:app:lintRelease
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
  #      - name: Upload build outputs
  #        if: success()
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: build-outputs
  #          path: app/build/outputs

  verify-snapshots:
    name: 📸 Verify snapshots
    needs: build
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: verifyPaparazziDebug
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy test results
        if: failure()
        run: |
          mkdir -p snapshot
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} snapshot/ \;

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot-results
          path: snapshot

  dep-diff:
    name: 👀 Dependency diff
    needs: verify-snapshots
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: android-app:app:dependencies --configuration debugRuntimeClasspath
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        with:
          configuration: 'debugRuntimeClasspath'
          project: 'android-app:app'
        env:
          GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff

      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff:
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
