name: PR
on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  code-linting:
    name: Code linting
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - name: SpotlessCheck
        run: |
          ./gradlew --no-daemon --scan --stacktrace spotlessCheck

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-tests

      - name: Tests and coverage
        run: |
          ./gradlew --continue --scan --stacktrace --no-daemon\
               testDebugUnitTest \
               koverXmlReport

      - name: Copy test results
        if: failure()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: junit-results
          path: junit

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: build/reports

      - name: Codecov coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate build number
        shell: bash
        run: echo "BUILD_NUMBER=$(expr $GITHUB_RUN_NUMBER + 5210)" >> $GITHUB_ENV

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-build

      - name: Build and check
        run: |
          ./gradlew -Pplayground.versioncode=$BUILD_NUMBER --scan --stacktrace --continue --no-daemon\
               app:assembleDebug \
               app:lintRelease
