name: PR
on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  code-linting:
    name: Code linting
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: KtlintCheck
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            ktlintCheck

  tests:
    name: Run tests
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Tests
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            testDebugUnitTest
            koverXmlReport

      - name: Copy test results
        if: failure()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: junit

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: build/reports/kover

      - name: Codecov coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate build number
        shell: bash
        run: echo "BUILD_NUMBER=$(expr $GITHUB_RUN_NUMBER + 5210)" >> $GITHUB_ENV

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Build and check
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            assertModuleGraph
            app:assembleDebug
            app:lintRelease

      - name: Upload build outputs
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs

  dep-diff:
    name: Dependency diff
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Dependencies
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            :app:dependencies --configuration debugRuntimeClasspath

      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        with:
          configuration: 'debugRuntimeClasspath'
          project: 'app'

      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff

      - uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff:
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
