name: Nightly
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Check dependency updates
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            --scan
            dependencyUpdates

#      - name: Upload dependency updates report
#        uses: actions/upload-artifact@v3
#        with:
#          name: dependency-updates
#          path: build/dependencyUpdates
