name: Nightly
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  dependecy-updates:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: burrunan/gradle-cache-action@v1
        name: Check dependency updates
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            dependencyUpdates

#      - name: Upload dependency updates report
#        uses: actions/upload-artifact@v3
#        with:
#          name: dependency-updates
#          path: build/dependencyUpdates
  gradle-rc:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - run: gradle build --dry-run # just test build configuration
