name: Nightly
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: Check dependency updates
        with:
          gradle-build-scan-report: true
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            dependencyUpdates

      - name: Upload dependency updates report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-updates
          path: build/dependencyUpdates